

#define INVENTORY_NONE				0
//armor
#define INVENTORY_ARMOR				1
//weapons
// FALCON : START : Added Q3F weapons
#define INVENTORY_AXE				2
#define INVENTORY_SHOTGUN			3
#define INVENTORY_SUPERSHOTGUN		4
#define INVENTORY_NAILGUN			5
#define INVENTORY_SUPERNAILGUN		6
#define INVENTORY_GRENADELAUNCHER	7
#define INVENTORY_ROCKETLAUNCHER	8
#define INVENTORY_SNIPERRIFLE		9
#define INVENTORY_RAILGUN			10
#define INVENTORY_FLAMETHROWER		11
#define INVENTORY_MINIGUN			12
#define INVENTORY_ASSAULTRIFLE		13
#define INVENTORY_DARTGUN			14
#define INVENTORY_PIPELAUNCHER		15
#define INVENTORY_NAPALMCANNON		16
#define INVENTORY_GRAPPLINGHOOK		17
/*#define INVENTORY_NAILGUN			15
#define INVENTORY_PROXLAUNCHER		16
#define INVENTORY_CHAINGUN			17*/
// FALCON : END
//ammo
#define INVENTORY_SHELLS			18
#define INVENTORY_NAILS				19
#define INVENTORY_GRENADES			20
#define INVENTORY_CELLS				21
#define INVENTORY_LIGHTNINGAMMO		22
#define INVENTORY_ROCKETS			23
#define INVENTORY_SLUGS				24
#define INVENTORY_BFGAMMO			25
//powerups
#define INVENTORY_HEALTH			26
#define INVENTORY_TELEPORTER		27
#define INVENTORY_MEDKIT			28
#define INVENTORY_QUAD				29
#define INVENTORY_ENVIRONMENTSUIT	30
#define INVENTORY_HASTE				31
#define INVENTORY_INVISIBILITY		32
#define INVENTORY_REGEN				33
#define INVENTORY_FLIGHT			34
#define INVENTORY_REDFLAG			35
#define INVENTORY_BLUEFLAG			36
//enemy stuff
#define ENEMY_HORIZONTAL_DIST		200
#define ENEMY_HEIGHT				201
#define NUM_VISIBLE_ENEMIES			202
#define NUM_VISIBLE_TEAMMATES		203

//item numbers (make sure they are in sync with bg_itemlist in bg_misc.c)
#define MODELINDEX_ARMORSHARD		1
#define MODELINDEX_ARMORCOMBAT		2
#define MODELINDEX_ARMORBODY		3
#define MODELINDEX_HEALTHSMALL		4
#define MODELINDEX_HEALTH			5
#define MODELINDEX_HEALTHLARGE		6
#define MODELINDEX_HEALTHMEGA		7

#define MODELINDEX_AXE				8
#define MODELINDEX_SHOTGUN			9
#define MODELINDEX_SUPERSHOTGUN		10
#define MODELINDEX_NAILGUN			11
#define MODELINDEX_SUPERNAILGUN		12
#define MODELINDEX_GRENADELAUNCHER	13
#define MODELINDEX_ROCKETLAUNCHER	15
#define MODELINDEX_SNIPERRIFLE		16
#define MODELINDEX_RAILGUN			17
#define MODELINDEX_FLAMETHROWER		18
#define MODELINDEX_MINIGUN			16
#define MODELINDEX_ASSAULTRIFLE		17
#define MODELINDEX_DARTGUN			18
#define MODELINDEX_PIPELAUNCHER		19
#define MODELINDEX_NAPALMCANNON		20
#define MODELINDEX_GRAPPLINGHOOK	21

#define MODELINDEX_SHELLS			22
#define MODELINDEX_NAILS			23
#define MODELINDEX_GRENADES			24
#define MODELINDEX_CELLS			25
#define MODELINDEX_LIGHTNINGAMMO	26
#define MODELINDEX_ROCKETS			27
#define MODELINDEX_SLUGS			28
#define MODELINDEX_BFGAMMO			29

#define MODELINDEX_TELEPORTER		30
#define MODELINDEX_MEDKIT			31
#define MODELINDEX_QUAD				32
#define MODELINDEX_ENVIRONMENTSUIT	33
#define MODELINDEX_HASTE			34
#define MODELINDEX_INVISIBILITY		35
#define MODELINDEX_REGEN			36
#define MODELINDEX_FLIGHT			37
#define MODELINDEX_REDFLAG			38
#define MODELINDEX_BLUEFLAG			39

// mission pack only defines

/*#define MODELINDEX_KAMIKAZE			36
#define MODELINDEX_PORTAL			37
#define MODELINDEX_INVULNERABILITY	38

#define MODELINDEX_NAILS			39
#define MODELINDEX_MINES			40
#define MODELINDEX_BELT				41

#define MODELINDEX_SCOUT			42
#define MODELINDEX_GUARD			43
#define MODELINDEX_DOUBLER			44
#define MODELINDEX_AMMOREGEN		45

#define MODELINDEX_NEUTRALFLAG		46
#define MODELINDEX_REDCUBE			47
#define MODELINDEX_BLUECUBE			48

#define MODELINDEX_NAILGUN			49
#define MODELINDEX_PROXLAUNCHER		50
#define MODELINDEX_CHAINGUN			51*/


//
#define WEAPONINDEX_GAUNTLET			1
#define WEAPONINDEX_MACHINEGUN			2
#define WEAPONINDEX_SHOTGUN				3
#define WEAPONINDEX_GRENADE_LAUNCHER	4
#define WEAPONINDEX_ROCKET_LAUNCHER		5
#define WEAPONINDEX_LIGHTNING			6
#define WEAPONINDEX_RAILGUN				7
#define WEAPONINDEX_PLASMAGUN			8
#define WEAPONINDEX_BFG					9
#define WEAPONINDEX_GRAPPLING_HOOK		10
/*#define WEAPONINDEX_NAILGUN				11
#define WEAPONINDEX_PROXLAUNCHER		12
#define WEAPONINDEX_CHAINGUN			13*/
